# docker-compose.yml
version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret-dev-password-3847953847
      POSTGRES_DB: mapmonitor
    volumes:
       - ./data
    ports:
      - "5432:5432"
