# Generated by Django 4.1.5 on 2023-02-11 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapalitics', '0002_user_mapaliticstoken_created_ts_trackevent_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrackEvent',
        ),
    ]
