# Generated by Django 4.1.5 on 2023-02-11 03:56

from django.db import migrations, models
import django.db.models.deletion
import time


class Migration(migrations.Migration):

    dependencies = [
        ('mapalitics', '0003_delete_trackevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(db_index=True, max_length=64)),
                ('map_uid', models.CharField(db_index=True, max_length=32)),
                ('race_time', models.IntegerField(db_index=True, default=-1)),
                ('created_ts', models.IntegerField(default=time.time, verbose_name='created timestamp')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mapalitics.user')),
            ],
        ),
    ]
