# Generated by Django 4.1.5 on 2023-02-11 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapalitics', '0004_trackevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackevent',
            name='cp_count',
            field=models.IntegerField(default=-1),
        ),
    ]
