# Generated by Django 4.1.5 on 2023-02-11 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapalitics', '0005_trackevent_cp_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackevent',
            name='px',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='trackevent',
            name='py',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='trackevent',
            name='pz',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='trackevent',
            name='vx',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='trackevent',
            name='vy',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='trackevent',
            name='vz',
            field=models.FloatField(default=-1),
        ),
    ]
