# Generated by Django 4.1.5 on 2023-02-11 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapalitics', '0007_zone_trackevent_zone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackevent',
            name='zone',
        ),
        migrations.DeleteModel(
            name='Zone',
        ),
    ]
