# Generated by Django 4.1.5 on 2023-01-10 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MapTotalPlayers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(db_index=True, max_length=32, unique=True)),
                ('nb_players', models.IntegerField(default=0, verbose_name='number of players')),
                ('last_highest_score', models.IntegerField(default=0)),
            ],
        ),
    ]
