# Generated by Django 4.1.5 on 2023-01-10 03:19

from django.db import migrations, models
import time


class Migration(migrations.Migration):

    dependencies = [
        ('getrecords', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maptotalplayers',
            name='created_ts',
            field=models.IntegerField(default=time.time, verbose_name='created timestamp'),
        ),
        migrations.AddField(
            model_name='maptotalplayers',
            name='last_update_started_ts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='maptotalplayers',
            name='updated_ts',
            field=models.IntegerField(default=time.time, verbose_name='updated timestamp'),
        ),
    ]
