# Generated by Django 4.1.5 on 2023-01-10 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getrecords', '0002_maptotalplayers_created_ts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_for', models.CharField(db_index=True, max_length=64, unique=True)),
                ('access_token', models.CharField(max_length=1024)),
                ('refresh_token', models.CharField(max_length=1024)),
                ('refresh_after', models.IntegerField()),
                ('expiry_ts', models.IntegerField()),
            ],
        ),
    ]
