# Generated by Django 4.1.5 on 2023-01-10 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getrecords', '0003_authtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnownOpenplanetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashed', models.CharField(db_index=True, max_length=64, unique=True)),
                ('account_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('display_name', models.CharField(db_index=True, max_length=64)),
                ('token_time', models.IntegerField()),
                ('expire_at', models.IntegerField()),
            ],
        ),
    ]
