# Generated by Django 4.1.5 on 2023-02-09 07:06

from django.db import migrations, models
import time


class Migration(migrations.Migration):

    dependencies = [
        ('getrecords', '0005_track_user_userstats_trackstats_ghost_usertrackplay'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='last_updated_ts',
            field=models.IntegerField(default=time.time),
        ),
        migrations.AlterField(
            model_name='track',
            name='map_id',
            field=models.CharField(db_index=True, max_length=48, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='name',
            field=models.TextField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='thumbnail_url',
            field=models.TextField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='url',
            field=models.TextField(max_length=256, null=True),
        ),
    ]
