# Generated by Django 4.1.5 on 2023-02-10 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('getrecords', '0007_ghost_size_bytes'),
    ]

    operations = [
        migrations.AddField(
            model_name='knownopenplanettoken',
            name='plugin_site_id',
            field=models.IntegerField(db_index=True, default=308),
        ),
        migrations.AlterField(
            model_name='knownopenplanettoken',
            name='account_id',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='knownopenplanettoken',
            name='hashed',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='trackstats',
            name='partial_runs',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='trackstats',
            name='total_runs',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='trackstats',
            name='unique_users',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='partial_runs',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='total_runs',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='unique_maps',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterUniqueTogether(
            name='knownopenplanettoken',
            unique_together={('account_id', 'plugin_site_id')},
        ),
        migrations.AlterIndexTogether(
            name='knownopenplanettoken',
            index_together={('account_id', 'plugin_site_id')},
        ),
        migrations.CreateModel(
            name='UserPrefs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_is_public', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='getrecords.user')),
            ],
        ),
    ]
