# Generated by Django 4.1.5 on 2023-02-11 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getrecords', '0008_knownopenplanettoken_plugin_site_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackstats',
            name='total_time',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='userstats',
            name='total_time',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
