# Generated by Django 4.1.5 on 2023-06-02 04:57

from django.db import migrations, models
import time


class Migration(migrations.Migration):

    dependencies = [
        ('getrecords', '0010_ghost_segmented_trackstats_segmented_runs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_id', models.IntegerField(db_index=True, unique=True, verbose_name='challenge id')),
                ('uid', models.CharField(db_index=True, max_length=32, unique=True)),
                ('name', models.CharField(db_index=True, max_length=64)),
                ('leaderboard_id', models.IntegerField(verbose_name='leaderboardId')),
                ('start_ts', models.IntegerField(db_index=True, verbose_name='start timestamp')),
                ('end_ts', models.IntegerField(db_index=True, verbose_name='end timestamp')),
                ('created_ts', models.IntegerField(default=time.time, verbose_name='created timestamp')),
                ('updated_ts', models.IntegerField(default=time.time, verbose_name='updated timestamp')),
            ],
        ),
        migrations.CreateModel(
            name='CotdQualiTimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_id', models.IntegerField(db_index=True, verbose_name='challenge id')),
                ('uid', models.CharField(db_index=True, max_length=32)),
                ('length', models.IntegerField(verbose_name='length')),
                ('offset', models.IntegerField(verbose_name='offset')),
                ('json_payload', models.TextField(default='[]', verbose_name='quali json sz')),
                ('created_ts', models.IntegerField(default=time.time, verbose_name='created timestamp')),
                ('updated_ts', models.IntegerField(default=time.time, verbose_name='updated timestamp')),
                ('last_update_started_ts', models.IntegerField(default=0)),
            ],
            options={
                'unique_together': {('challenge_id', 'uid', 'length', 'offset')},
            },
        ),
    ]
