# Generated by Django 4.1.5 on 2023-06-24 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getrecords', '0012_alter_challenge_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='TmxMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TrackID', models.IntegerField(db_index=True)),
                ('UserID', models.IntegerField(db_index=True)),
                ('Username', models.CharField(db_index=True, max_length=32)),
                ('AuthorLogin', models.CharField(db_index=True, max_length=32)),
                ('Name', models.CharField(max_length=128)),
                ('GbxMapName', models.CharField(max_length=128)),
                ('TrackUID', models.CharField(db_index=True, max_length=32)),
                ('TitlePack', models.CharField(db_index=True, max_length=64)),
                ('ExeVersion', models.CharField(db_index=True, max_length=32)),
                ('ExeBuild', models.CharField(db_index=True, max_length=32)),
                ('Mood', models.CharField(max_length=32)),
                ('ModName', models.CharField(max_length=128, null=True)),
                ('AuthorTime', models.IntegerField()),
                ('ParserVersion', models.IntegerField()),
                ('UploadedAt', models.CharField(max_length=32)),
                ('UpdatedAt', models.CharField(max_length=32)),
                ('UploadTimestamp', models.FloatField()),
                ('UpdateTimestamp', models.FloatField()),
                ('Tags', models.CharField(max_length=32, null=True)),
                ('TypeName', models.CharField(max_length=32)),
                ('StyleName', models.CharField(db_index=True, max_length=32, null=True)),
                ('RouteName', models.CharField(max_length=32)),
                ('LengthName', models.CharField(max_length=32)),
                ('LengthSecs', models.IntegerField(db_index=True)),
                ('LengthEnum', models.IntegerField()),
                ('DifficultyName', models.CharField(max_length=32)),
                ('DifficultyInt', models.IntegerField(null=True)),
                ('Laps', models.IntegerField()),
                ('Comments', models.TextField()),
                ('Downloadable', models.BooleanField()),
                ('Unlisted', models.BooleanField()),
                ('Unreleased', models.BooleanField()),
                ('RatingVoteCount', models.IntegerField()),
                ('RatingVoteAverage', models.FloatField()),
                ('VehicleName', models.CharField(max_length=32)),
                ('EnvironmentName', models.CharField(max_length=32)),
                ('HasScreenshot', models.BooleanField()),
                ('HasThumbnail', models.BooleanField()),
                ('MapType', models.CharField(max_length=32, null=True)),
                ('WasTOTD', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TmxMapScrapeState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=16)),
                ('LastScraped', models.IntegerField()),
            ],
        ),
    ]
