# Generated by Django 4.2.2 on 2023-06-25 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getrecords', '0013_tmxmap_tmxmapscrapestate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmxmap',
            name='AuthorLogin',
            field=models.CharField(db_index=True, max_length=64),
        ),
    ]
