# Generated by Django 4.2.2 on 2023-06-25 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getrecords', '0014_alter_tmxmap_authorlogin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmxmap',
            name='TrackUID',
            field=models.CharField(db_index=True, max_length=32, null=True),
        ),
    ]
