# Generated by Django 4.2.2 on 2023-06-25 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getrecords', '0015_alter_tmxmap_trackuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmxmap',
            name='AuthorTime',
            field=models.IntegerField(null=True),
        ),
    ]
