# Generated by Django 4.2.2 on 2023-06-25 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getrecords', '0016_alter_tmxmap_authortime'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmxmap',
            name='AwardCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tmxmap',
            name='ImageCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tmxmap',
            name='IsMP4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tmxmap',
            name='TrackValue',
            field=models.IntegerField(default=0),
        ),
    ]
