# Generated by Django 4.2.2 on 2023-06-25 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getrecords', '0017_tmxmap_awardcount_tmxmap_imagecount_tmxmap_ismp4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmxmap',
            name='DisplayCost',
            field=models.IntegerField(default=0),
        ),
    ]
