# Generated by Django 4.2.2 on 2023-07-07 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('getrecords', '0018_tmxmap_displaycost'),
    ]

    operations = [
        migrations.CreateModel(
            name='TmxMapAT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UploadedToNadeo', models.BooleanField(default=False)),
                ('AuthorTimeBeaten', models.BooleanField(default=False)),
                ('ATBeatenTimestamp', models.IntegerField(default=-1)),
                ('ATBeatenUsers', models.TextField(default='')),
                ('Track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getrecords.tmxmap')),
            ],
        ),
    ]
