# Generated by Django 4.2.2 on 2023-07-07 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('getrecords', '0020_alter_tmxmapat_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmxmapat',
            name='Track',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='getrecords.tmxmap'),
        ),
    ]
