# Generated by Django 4.2.2 on 2023-07-07 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getrecords', '0021_alter_tmxmapat_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmxmapat',
            name='Broken',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tmxmapat',
            name='LastChecked',
            field=models.FloatField(default=0),
        ),
    ]
