# Generated by Django 4.2.2 on 2023-07-07 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getrecords', '0022_tmxmapat_broken_tmxmapat_lastchecked'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmxmapat',
            name='WR',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='tmxmapat',
            name='WR_Player',
            field=models.CharField(default='', max_length=40),
        ),
    ]
