# Generated by Django 4.2.2 on 2023-07-11 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getrecords', '0024_alter_tmxmap_trackid'),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=32, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.TextField()),
            ],
        ),
    ]
