# Generated by Django 4.2.2 on 2023-07-12 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getrecords', '0027_tmxmapat_unbeatable'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmxmapat',
            name='ATBeatenFirstNb',
            field=models.IntegerField(db_index=True, default=-1),
        ),
    ]
