# Generated by Django 4.2.2 on 2023-07-12 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getrecords', '0028_tmxmapat_atbeatenfirstnb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmxmapat',
            name='AuthorTimeBeaten',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='tmxmapat',
            name='Broken',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='tmxmapat',
            name='LastChecked',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='tmxmapat',
            name='RemovedFromTmx',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='tmxmapat',
            name='Unbeatable',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
