# Generated by Django 4.2.2 on 2023-07-13 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getrecords', '0030_tmxmap_replaywrid_tmxmap_replaywrtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmxmapat',
            name='ATBeatenOnTmx',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='tmxmapat',
            name='TmxReplayVerified',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
