# Generated by Django 4.2.2 on 2023-09-18 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getrecords', '0032_cotdchallenge_cotdchallengeranking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cotdchallenge',
            options={'ordering': ['-challenge_id', '-start_date']},
        ),
    ]
