# Generated by Django 4.2.2 on 2023-09-21 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getrecords', '0034_cotdchallenge_leaderboard_id_cotdchallenge_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cotdchallengeranking',
            unique_together={('req_timestamp', 'rank', 'challenge')},
        ),
    ]
