# Generated by Django 4.2.2 on 2023-09-21 00:24

from django.db import migrations
from django.db.models import Min, Count

from getrecords.models import CotdChallengeRanking

def delete_challenge_record_duplicates(apps, schema_editor):
    non_dupe_pks = list(
        CotdChallengeRanking.objects.values('challenge', 'req_timestamp', 'rank')
            .annotate(Min('pk'), count=Count('pk'))
            .order_by()
            .values_list('pk__min', flat=True)
    )

    dupes = CotdChallengeRanking.objects.exclude(pk__in=non_dupe_pks)
    dupes.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('getrecords', '0034_cotdchallenge_leaderboard_id_cotdchallenge_name'),
    ]

    operations = [
        migrations.RunPython(delete_challenge_record_duplicates),
        migrations.AlterUniqueTogether(
            name='cotdchallengeranking',
            unique_together={('req_timestamp', 'rank', 'challenge')},
        ),
    ]
