# Generated by Django 4.2.2 on 2024-10-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getrecords', '0035_alter_cotdchallengeranking_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='TmxUnbeatenMapPackUpdated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.FloatField(db_index=True, default=0)),
            ],
        ),
        migrations.AlterIndexTogether(
            name='cotdchallengeranking',
            index_together={('challenge', 'req_timestamp')},
        ),
    ]
