# Generated by Django 4.2.2 on 2024-10-03 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getrecords', '0036_tmxunbeatenmappackupdated_and_more'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='cotdchallengeranking',
            index_together=set(),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='total_time',
            field=models.IntegerField(default=0),
        ),
    ]
