# Generated by Django 4.2.2 on 2024-10-04 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getrecords', '0037_alter_cotdchallengeranking_index_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TmxMapPackTrackUpdateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TrackID', models.IntegerField(db_index=True)),
                ('PackID', models.IntegerField(db_index=True)),
                ('last_updated', models.FloatField(db_index=True, default=0)),
            ],
            options={
                'unique_together': {('TrackID', 'PackID')},
            },
        ),
        migrations.DeleteModel(
            name='TmxUnbeatenMapPackUpdated',
        ),
    ]
