# Generated by Django 4.2.2 on 2025-01-09 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getrecords', '0039_alter_tmxmap_index_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmxmap',
            name='RatingVoteAverage',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='tmxmap',
            name='RatingVoteCount',
            field=models.IntegerField(null=True),
        ),
    ]
